export const categoryData = [
    {
        id: "CAT-1001",
        name: "Electronics",
        description: "Electronic devices and accessories",
        productCount: 156,
        lastUpdated: "Apr 10, 2024",
    },
    {
        id: "CAT-1002",
        name: "Clothing",
        description: "Apparel and fashion items",
        productCount: 243,
        lastUpdated: "Apr 12, 2024",
    },
    {
        id: "CAT-1003",
        name: "Home & Kitchen",
        description: "Furniture, appliances, and home decor",
        productCount: 189,
        lastUpdated: "Apr 8, 2024",
    },
    {
        id: "CAT-1004",
        name: "Books",
        description: "Books, ebooks, and audiobooks",
        productCount: 112,
        lastUpdated: "Apr 5, 2024",
    },
    {
        id: "CAT-1005",
        name: "Sports & Outdoors",
        description: "Sporting goods and outdoor equipment",
        productCount: 98,
        lastUpdated: "Apr 15, 2024",
    },
    {
        id: "CAT-1006",
        name: "Beauty & Personal Care",
        description: "Cosmetics, skincare, and personal grooming products",
        productCount: 176,
        lastUpdated: "Apr 3, 2024",
    },
    {
        id: "CAT-1007",
        name: "Toys & Games",
        description: "Toys, games, and entertainment items for kids",
        productCount: 84,
        lastUpdated: "Apr 7, 2024",
    },
    {
        id: "CAT-1008",
        name: "Automotive",
        description: "Car parts, accessories, and tools",
        productCount: 42,
        lastUpdated: "Mar 25, 2024",
    },
];
